# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/miuicamera/common/proprietary/etc/device_features/chiron.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/device_features/chiron.xml \
    vendor/miuicamera/common/proprietary/etc/device_features/sagit.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/device_features/sagit.xml \
    vendor/miuicamera/common/proprietary/etc/device_features/tulip.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/device_features/tulip.xml \
    vendor/miuicamera/common/proprietary/etc/device_features/platina.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/device_features/platina.xml \
    vendor/miuicamera/common/proprietary/etc/permissions/com.android.camera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.camera.xml \
    vendor/miuicamera/common/proprietary/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so \
    vendor/miuicamera/common/proprietary/priv-app/MiuiCamera/lib/arm64/libmorpho_memory_allocator.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmorpho_memory_allocator.so \
    vendor/miuicamera/common/proprietary/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama.so \
    vendor/miuicamera/common/proprietary/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama_gp.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama_gp.so

PRODUCT_PACKAGES += \
    MiuiCamera
